name: Auto-merge Dependabot PRs

on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Auto-merge Dependabot PR
        uses: fastify/github-action-merge-dependabot@v3.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
